### ISSUE TITLE
log Recurring content

### ISSUE THREAD

**Issue by al-wei** [Meldexun/RenderLib#41]
RenderLib-1.12.2-1.3.5

Forge: Forge 14.23.5.2860
Minecraft: 1.12.2

Hardware
CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz 2.30 GHz 8core 16
RAM: 16GB3200MHz/Allocate memory8G
GPU: NVIDIA GeForce RTX 3060 Laptop GPU
VRAM: 6G

[22:45:27] [Thread-6/ERROR] [renderlib]: OpenGL API Error High 1280 GL_INVALID_ENUM error generated. <cap> enum is invalid; expected GL_ALPHA_TEST, GL_BLEND, GL_COLOR_MATERIAL, GL_CULL_FACE, GL_DEPTH_TEST, GL_DITHER, GL_FOG, etc. (136 others).
	at meldexun.renderlib.opengl.debug.OpenGLDebugMode.log(OpenGLDebugMode.java:396)
	at meldexun.renderlib.opengl.debug.OpenGLDebugMode.log(OpenGLDebugMode.java:373)
	at org.lwjgl.opengl.GL11.nglEnable(GL11.java:-2)
	at org.lwjgl.opengl.GL11.glEnable(GL11.java:1015)
	at alexiil.mc.mod.load.render.MinecraftDisplayerRenderer.render(MinecraftDisplayerRenderer.java:123)
	at alexiil.mc.mod.load.ClsManager.renderFrame(ClsManager.java:186)
	at alexiil.mc.mod.load.render.MainSplashRenderer.renderFrame(MainSplashRenderer.java:296)
	at alexiil.mc.mod.load.render.MainSplashRenderer.run(MainSplashRenderer.java:216)
	at net.minecraftforge.fml.client.SplashProgress$2.run(SplashProgress.java:260)
	at java.lang.Thread.run(null:-1)

**Comment by Meldexun** [comment]
Please make use of the issue template. Either edit this issue and reopen it or create a new one.
