### ISSUE TITLE
[1.12] ConcurrentModificationException on teleporting

### ISSUE THREAD

**Issue by Krutoy242** [Meldexun/RenderLib#7]
Client crashes randomly on teleport to new point.

In most cases error happen with this stack trace (can be seen in attached `debug.log`):
```less
java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at net.minecraft.client.renderer.EntityRenderer.handler$zdg000$renderWorld(EntityRenderer.java:4249)
```

There is no RenderLib mention, but removing RenderLib fixes crashes.

Another variation of same crash looks like this:
```less
java.util.ConcurrentModificationException
    at java.util.ArrayList.forEach(ArrayList.java:1252)
    at meldexun.renderlib.renderer.tileentity.TileEntityRenderer.fillTileEntityLists(TileEntityRenderer.java:40)
    at meldexun.renderlib.renderer.tileentity.TileEntityRendererOptifine.fillTileEntityLists(TileEntityRendererOptifine.java:26)
    at meldexun.renderlib.renderer.tileentity.TileEntityRenderer.setup(TileEntityRenderer.java:30)
    at meldexun.renderlib.renderer.tileentity.TileEntityRendererOptifine.setup(TileEntityRendererOptifine.java:18)
    at meldexun.renderlib.renderer.TileEntityRenderManager.setup(TileEntityRenderManager.java:14)
    at net.minecraft.client.renderer.RenderGlobal.handler$zdm001$setupTerrain(RenderGlobal.java:6261)
```

**To Reproduce**

This issue cant be reproduced stably on different machines. On some machines it never happens.

1. Teleport to point out of render distance
2. Use elevator (move player up or down)

This happens to ~5% of players of my modpack [E2E-E](https://github.com/Krutoy242/Enigmatica2Expert-Extended).
One of players with this issue who sent me logs: https://github.com/cannonsloan

**Additional info**
- Settings like *chunk updates* and *render distance* didn't seem to have an impact
- Removing Optifine has no effect
- Removing EntityCulling has no effect
- Clearing all entities `/cofh killall *` has no effect (we though there was erroring entities)
- Raise or lower the amounts of allocated RAM has no effect
- Stopping using resource packs and shaders has no effect

**Versions**
RenderLib: `1.0.8`
Forge: `14.23.5.2860`
Minecraft: `1.12.2`
Other mods: [About 400 mods](https://www.curseforge.com/minecraft/modpacks/enigmatica-2-expert-extended)

**Log File**

**Comment by Meldexun** [comment]
Should be fixed in v1.12.2-1.1.0
